name: Remote service probe (self-hosted)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  probe:
    runs-on: [self-hosted, btc-da, linux, x64]
    timeout-minutes: 15

    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      RPC_USER: ${{ secrets.RPC_USER }}
      RPC_PASSWORD: ${{ secrets.RPC_PASSWORD }}
      PODA_URL: ${{ secrets.PODA_URL }}
      WALLET: ${{ secrets.WALLET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --locked --workspace --all-targets --verbose

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets -- -D warnings

      - name: e2e test
        run: cargo run --locked --bin main
